import {ChangeDetectorRef,Component,OnInit} from '@angular/core';import {FormArray,FormBuilder,Validators} from '@angular/forms';import {InventoryItem} from '../../models/inventory.model';import {ArticleService} from '../../services/article.service';import {Station} from '../../services/station';import {DropdownOption} from '../../shared/dropdown/dropdown';
@Component({selector:'app-inventory',standalone:false,templateUrl:'./inventory.html',styleUrl:'./inventory.scss'})
export class Inventory implements OnInit{
 items:InventoryItem[]=[];stations:DropdownOption[]=[];stationId=0;loading=true;filter:'all'|'alert'|'available'='all';query='';adjusting:InventoryItem|null=null;saving=false;stocktakeOpen=false;stocktakeSaving=false;form;stocktakeForm;
 constructor(private service:Station,private articles:ArticleService,private fb:FormBuilder,private cdr:ChangeDetectorRef){this.form=fb.nonNullable.group({type:['ADD' as 'ADD'|'REMOVE'|'SET',Validators.required],quantity:[0,[Validators.required,Validators.min(.000001)]],reason:['',[Validators.required,Validators.minLength(3)]]});this.stocktakeForm=fb.group({reference:['',Validators.required],reason:['Inventaire physique',[Validators.required,Validators.minLength(3)]],lines:fb.array([])})}
 get stocktakeLines(){return this.stocktakeForm.controls.lines as FormArray}
 ngOnInit(){this.articles.options().subscribe(x=>{this.stations=x.stations.map(s=>({value:s.id,label:s.name,hint:'Inventaire de la station'}));this.stationId=x.stations[0]?.id??0;this.load();this.cdr.detectChanges()})}
 load(){if(!this.stationId){this.loading=false;return}this.loading=true;this.service.inventory(this.stationId).subscribe({next:x=>{this.items=x;this.loading=false;this.cdr.detectChanges()},error:()=>{this.loading=false;this.cdr.detectChanges()}})}
 get visible(){const q=this.query.trim().toLowerCase();return this.items.filter(x=>(!q||`${x.article} ${x.category}`.toLowerCase().includes(q))&&(this.filter==='all'||this.filter==='alert'&&x.alert||this.filter==='available'&&!x.alert))}
 get alerts(){return this.items.filter(x=>x.alert).length}get totalStock(){return this.items.reduce((sum,x)=>sum+x.currentStock,0)}
 equivalents(item:InventoryItem,quantity=item.currentStock){return (item.units??[]).slice().sort((a,b)=>b.conversionFactor-a.conversionFactor).map(u=>({label:u.symbol||u.name,value:u.conversionFactor?quantity/u.conversionFactor:0,isBase:u.isBaseUnit}))}
 lineEquivalents(index:number){const item=this.items.find(x=>x.id===this.stocktakeLines.at(index).value.id);return item?this.equivalents(item,Number(this.stocktakeLines.at(index).value.systemQuantity)):[]}
 openAdjust(item:InventoryItem){this.adjusting=item;this.form.reset({type:'ADD',quantity:0,reason:''})}closeAdjust(){if(!this.saving)this.adjusting=null}
 projected():number{if(!this.adjusting)return 0;const q=Number(this.form.value.quantity)||0;return this.form.value.type==='SET'?q:this.form.value.type==='REMOVE'?Math.max(0,this.adjusting.currentStock-q):this.adjusting.currentStock+q}
 save(){if(!this.adjusting||this.form.invalid){this.form.markAllAsTouched();return}this.saving=true;this.service.adjustStock(this.adjusting.id,this.form.getRawValue()).subscribe({next:x=>{this.items=this.items.map(i=>i.id===x.id?x:i);this.adjusting=null;this.saving=false;this.cdr.detectChanges()},error:()=>{this.saving=false;this.cdr.detectChanges()}})}
 openStocktake(){this.stocktakeLines.clear();this.items.filter(i=>i.active).forEach(i=>{const units=i.units??[];const counts=this.fb.array(units.map(u=>this.fb.nonNullable.group({articleUnitId:[u.articleUnitId],name:[u.name],symbol:[u.symbol??u.name],conversionFactor:[u.conversionFactor],isBaseUnit:[u.isBaseUnit],quantity:[u.isBaseUnit?i.currentStock:0,[Validators.required,Validators.min(0)]]})));this.stocktakeLines.push(this.fb.group({id:[i.id],article:[i.article],category:[i.category],systemQuantity:[i.currentStock],counts}))});this.stocktakeForm.patchValue({reference:this.makeReference(),reason:'Inventaire physique'});this.stocktakeOpen=true;this.cdr.detectChanges()}
 makeReference(){const d=new Date();const pad=(n:number)=>String(n).padStart(2,'0');return `INV-${this.stationId}-${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}`}
 closeStocktake(){if(!this.stocktakeSaving){this.stocktakeOpen=false;this.stocktakeLines.clear();this.cdr.detectChanges()}}
 countControls(index:number){return this.stocktakeLines.at(index).get('counts') as FormArray}
 physicalBase(index:number){return this.countControls(index).controls.reduce((sum,c)=>sum+Number(c.value.quantity||0)*Number(c.value.conversionFactor||1),0)}
 difference(index:number){const l=this.stocktakeLines.at(index).value;return this.physicalBase(index)-Number(l.systemQuantity)}get changedLines(){return this.stocktakeLines.controls.filter((_,i)=>Math.abs(this.difference(i))>.0000001).length}
 validateStocktake(){if(this.stocktakeForm.invalid){this.stocktakeForm.markAllAsTouched();return}this.stocktakeSaving=true;const v=this.stocktakeForm.getRawValue();this.service.validateStocktake({stationId:this.stationId,reference:v.reference??'',reason:v.reason??'',lines:v.lines.map((l:any)=>({id:l.id,counts:l.counts.map((c:any)=>({articleUnitId:Number(c.articleUnitId),quantity:Number(c.quantity)}))}))}).subscribe({next:x=>{this.items=x;this.stocktakeSaving=false;this.stocktakeOpen=false;this.stocktakeForm.reset();this.stocktakeLines.clear();this.cdr.detectChanges()},error:()=>{this.stocktakeSaving=false;this.cdr.detectChanges()}})}
}
