<?php
namespace App\Controller;
use App\Entity\{FuelNozzle,FuelPump,FuelTank,FuelType,PumpAttendant,Stations};use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\{JsonResponse,Request};use Symfony\Component\Routing\Attribute\Route;
#[Route('/api/fuel/config')]
final class FuelConfigController extends AbstractController{
 #[Route('',methods:['GET'])]public function list(Request $r,EntityManagerInterface $em):JsonResponse{$sid=(int)$r->query->get('station');$station=$em->getRepository(Stations::class)->find($sid);if(!$station)return $this->json(['message'=>'Station invalide'],422);$fuels=$em->getRepository(FuelType::class)->findBy([],['code'=>'ASC']);$tanks=$em->getRepository(FuelTank::class)->findBy(['station'=>$sid],['name'=>'ASC']);$pumps=$em->getRepository(FuelPump::class)->findBy(['station'=>$sid],['name'=>'ASC']);$attendants=$em->getRepository(PumpAttendant::class)->findBy(['station'=>$sid],['fullName'=>'ASC']);$nozzles=[];foreach($em->getRepository(FuelNozzle::class)->findAll() as $x)if($x->getPump()?->getStation()?->getId()===$sid)$nozzles[]=$x;return $this->json(['fuels'=>array_map(fn($x)=>['id'=>$x->getId(),'code'=>$x->getCode(),'name'=>$x->getName(),'active'=>$x->isActive()],$fuels),'tanks'=>array_map(fn($x)=>['id'=>$x->getId(),'code'=>$x->getCode(),'name'=>$x->getName(),'fuel'=>$x->getFuelType()?->getCode(),'fuelTypeId'=>$x->getFuelType()?->getId(),'capacity'=>(float)$x->getCapacity(),'stock'=>(float)$x->getCurrentStock(),'minimum'=>(float)$x->getMinimumStock(),'active'=>$x->isActive()],$tanks),'pumps'=>array_map(fn($x)=>['id'=>$x->getId(),'code'=>$x->getCode(),'name'=>$x->getName(),'active'=>$x->isActive()],$pumps),'nozzles'=>array_map(fn($x)=>['id'=>$x->getId(),'code'=>$x->getCode(),'pump'=>$x->getPump()?->getName(),'pumpId'=>$x->getPump()?->getId(),'tank'=>$x->getTank()?->getName(),'tankId'=>$x->getTank()?->getId(),'currentIndex'=>(float)$x->getCurrentIndex(),'unitPrice'=>(float)$x->getUnitPrice(),'active'=>$x->isActive()],$nozzles),'attendants'=>array_map(fn($x)=>['id'=>$x->getId(),'code'=>$x->getCode(),'name'=>$x->getFullName(),'contact'=>$x->getContact(),'active'=>$x->isActive()],$attendants)]);}
 #[Route('/{type}/{id}',requirements:['id'=>'\\d+'],methods:['PUT'])]public function update(string $type,int $id,Request $r,EntityManagerInterface $em):JsonResponse{$d=$r->toArray();$e=$this->find($type,$id,$em);if(!$e)return $this->json(['message'=>'Élément introuvable'],404);$code=trim((string)($d['code']??''));$name=trim((string)($d['name']??''));if($e instanceof FuelType){$e->setCode($code)->setName($name);}elseif($e instanceof FuelTank){$fuel=$em->getRepository(FuelType::class)->find((int)($d['fuelTypeId']??0));if(!$fuel)return $this->json(['message'=>'Carburant invalide'],422);$e->setCode($code)->setName($name)->setFuelType($fuel)->setCapacity((string)max(0,(float)($d['capacity']??0)))->setMinimumStock((string)max(0,(float)($d['minimumStock']??0)));}elseif($e instanceof FuelPump){$e->setCode($code)->setName($name);}elseif($e instanceof FuelNozzle){$pump=$em->getRepository(FuelPump::class)->find((int)($d['pumpId']??0));$tank=$em->getRepository(FuelTank::class)->find((int)($d['tankId']??0));if(!$pump||!$tank)return $this->json(['message'=>'Pompe ou cuve invalide'],422);$e->setCode($code)->setPump($pump)->setTank($tank)->setCurrentIndex((string)max(0,(float)($d['currentIndex']??0)))->setUnitPrice((string)max(0,(float)($d['unitPrice']??0)));}elseif($e instanceof PumpAttendant){$e->setCode($code?:null)->setFullName($name)->setContact(trim((string)($d['contact']??''))?:null);}$em->flush();return $this->json(['id'=>$id]);}
 #[Route('/{type}/{id}/deactivate',requirements:['id'=>'\\d+'],methods:['PATCH'])]public function deactivate(string $type,int $id,EntityManagerInterface $em):JsonResponse{$e=$this->find($type,$id,$em);if(!$e)return $this->json(['message'=>'Élément introuvable'],404);$e->setIsActive(false);$em->flush();return $this->json(['id'=>$id,'active'=>false]);}
 private function find(string $type,int $id,EntityManagerInterface $em):object|null{$class=match($type){'fuel'=>FuelType::class,'tank'=>FuelTank::class,'pump'=>FuelPump::class,'nozzle'=>FuelNozzle::class,'attendant'=>PumpAttendant::class,default=>null};return $class?$em->getRepository($class)->find($id):null;}
}
