<?php
namespace App\Controller;
use App\Entity\{FuelDelivery,FuelShiftReading,FuelTank,Stations,Supplier,SupplierInvoice,SupplierPayment};use App\Service\UserAccessService;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\{JsonResponse,Request};use Symfony\Component\Routing\Attribute\Route;
#[Route('/api/suppliers')]
final class SupplierController extends AbstractController{
 #[Route('',methods:['GET'])]public function index(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;$sid=(int)$r->query->get('station');if(!$access->canAccessStation($sid))return$access->denyStation();$suppliers=$em->getRepository(Supplier::class)->findBy(['station'=>$sid],['name'=>'ASC']);$invoices=$em->getRepository(SupplierInvoice::class)->findBy(['station'=>$sid,'isActive'=>true],['invoiceDate'=>'DESC']);$payments=$em->getRepository(SupplierPayment::class)->findBy(['station'=>$sid,'status'=>'EXECUTED'],['paymentDate'=>'DESC']);$paidByInvoice=[];foreach($payments as $p)if($p->getInvoice())$paidByInvoice[$p->getInvoice()->getId()]=($paidByInvoice[$p->getInvoice()->getId()]??0)+(float)$p->getAmount();$rows=[];foreach($suppliers as $s){$billed=0;$paid=0;foreach($invoices as $i)if($i->getSupplier()?->getId()===$s->getId())$billed+=(float)$i->getTotalAmount();foreach($payments as $p)if($p->getSupplier()?->getId()===$s->getId())$paid+=(float)$p->getAmount();$rows[]=['id'=>$s->getId(),'code'=>$s->getCode(),'name'=>$s->getName(),'contactPerson'=>$s->getContactPerson(),'phone'=>$s->getPhone(),'email'=>$s->getEmail(),'address'=>$s->getAddress(),'active'=>$s->isActive(),'billed'=>$billed,'paid'=>$paid,'balance'=>$billed-$paid];}return $this->json(['suppliers'=>$rows,'invoices'=>array_map(function($i)use($paidByInvoice){$total=(float)$i->getTotalAmount();$paid=$paidByInvoice[$i->getId()]??0;$remaining=max(0,$total-$paid);$overdue=$i->getDueDate()&&$i->getDueDate()<new \DateTimeImmutable('today')&&$remaining>0;return['id'=>$i->getId(),'supplierId'=>$i->getSupplier()?->getId(),'supplier'=>$i->getSupplier()?->getName(),'number'=>$i->getInvoiceNumber(),'date'=>$i->getInvoiceDate()?->format('Y-m-d'),'dueDate'=>$i->getDueDate()?->format('Y-m-d'),'type'=>$i->getInvoiceType(),'description'=>$i->getDescription(),'total'=>$total,'paid'=>$paid,'remaining'=>$remaining,'status'=>$remaining<=.01?'PAID':($paid>0?'PARTIAL':($overdue?'OVERDUE':'UNPAID'))];},$invoices)]);}
 #[Route('',methods:['POST'])]public function create(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;$d=$r->toArray();$station=$em->getRepository(Stations::class)->find((int)($d['stationId']??0));$name=trim((string)($d['name']??''));if($station&&!$access->canAccessStation($station))return$access->denyStation();if(!$station||$name==='')return $this->json(['message'=>'Station et nom obligatoires'],422);$s=(new Supplier())->setStation($station)->setName($name)->setCode(trim((string)($d['code']??''))?:null)->setContactPerson(trim((string)($d['contactPerson']??''))?:null)->setPhone(trim((string)($d['phone']??''))?:null)->setEmail(trim((string)($d['email']??''))?:null)->setAddress(trim((string)($d['address']??''))?:null)->setCreatedAt(new \DateTimeImmutable());$em->persist($s);$em->flush();return $this->json(['id'=>$s->getId(),'name'=>$s->getName()],201);}
 #[Route('/delivery',methods:['POST'])]public function delivery(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;$d=$r->toArray();$station=$em->getRepository(Stations::class)->find((int)($d['stationId']??0));$supplier=$em->getRepository(Supplier::class)->find((int)($d['supplierId']??0));$tank=$em->getRepository(FuelTank::class)->find((int)($d['tankId']??0));$qty=max(0,(float)($d['quantity']??0));$cost=max(0,(float)($d['unitCost']??0));$number=trim((string)($d['invoiceNumber']??''));if($station&&!$access->canAccessStation($station))return$access->denyStation();if(!$station||!$supplier||!$tank||$supplier->getStation()?->getId()!==$station->getId()||$tank->getStation()?->getId()!==$station->getId()||$qty<=0||$number==='')return $this->json(['message'=>'Fournisseur, cuve, facture et quantité obligatoires'],422);if((float)$tank->getCurrentStock()+$qty>(float)$tank->getCapacity())return $this->json(['message'=>'Capacité de cuve dépassée'],422);$date=new \DateTimeImmutable($d['date']??'today');$total=round($qty*$cost,2);$delivery=(new FuelDelivery())->setStation($station)->setTank($tank)->setSupplier($supplier->getName())->setInvoiceNumber($number)->setDeliveryDate($date)->setQuantity((string)$qty)->setUnitCost((string)$cost)->setTotalAmount((string)$total)->setCreatedAt(new \DateTimeImmutable());$invoice=(new SupplierInvoice())->setSupplier($supplier)->setStation($station)->setDelivery($delivery)->setInvoiceNumber($number)->setInvoiceDate($date)->setDueDate(!empty($d['dueDate'])?new \DateTimeImmutable($d['dueDate']):null)->setTotalAmount((string)$total)->setDescription('Livraison '.$tank->getFuelType()?->getCode().' - '.$qty.' L')->setCreatedAt(new \DateTimeImmutable());$tank->setCurrentStock((string)((float)$tank->getCurrentStock()+$qty));$em->persist($delivery);$em->persist($invoice);$em->flush();return $this->json(['deliveryId'=>$delivery->getId(),'invoiceId'=>$invoice->getId()],201);}
 #[Route('/payments',methods:['POST'])]public function payment(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;$d=$r->toArray();$invoice=$em->getRepository(SupplierInvoice::class)->find((int)($d['invoiceId']??0));$amount=max(0,(float)($d['amount']??0));if($invoice&&!$access->canAccessStation($invoice->getStation()))return$access->denyStation();if(!$invoice||$amount<=0)return $this->json(['message'=>'Facture et montant obligatoires'],422);$already=0;foreach($em->getRepository(SupplierPayment::class)->findBy(['invoice'=>$invoice,'status'=>'EXECUTED'])as$p)$already+=(float)$p->getAmount();if($amount>(float)$invoice->getTotalAmount()-$already+.01)return $this->json(['message'=>'Le paiement dépasse le solde de la facture'],422);$p=(new SupplierPayment())->setSupplier($invoice->getSupplier())->setInvoice($invoice)->setStation($invoice->getStation())->setPaymentDate(new \DateTimeImmutable($d['date']??'today'))->setAmount((string)$amount)->setPaymentMethod((string)($d['method']??'BANK_TRANSFER'))->setReference(trim((string)($d['reference']??''))?:null)->setNote(trim((string)($d['note']??''))?:null)->setCreatedAt(new \DateTimeImmutable());$em->persist($p);$em->flush();return $this->json(['id'=>$p->getId()],201);}
 #[Route('/deductions',methods:['GET'])]
 public function deductions(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse
 {
  if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;
  $sid=(int)$r->query->get('station');$station=$em->getRepository(Stations::class)->find($sid);
  if(!$station)return $this->json(['message'=>'Station invalide'],422);
  if(!$access->canAccessStation($station))return$access->denyStation();
  $receipts=$em->getRepository(SupplierPayment::class)->findBy(['station'=>$station,'status'=>'RECEIVED'],['paymentDate'=>'DESC','id'=>'DESC']);
  $bySource=[];foreach($receipts as $receipt){$key=$receipt->getSourceReadingId().':'.$receipt->getSourcePaymentIndex();$bySource[$key][]=$receipt;}
  $rows=[];$readings=$em->getRepository(FuelShiftReading::class)->findBy(['station'=>$station],['workDate'=>'DESC','id'=>'DESC']);
  foreach($readings as $reading)foreach($reading->getPayments() as $index=>$line){if(empty($line['supplierDeduction']))continue;$key=$reading->getId().':'.$index;$sourceReceipts=$bySource[$key]??[];$amount=(float)($line['amount']??0);$received=array_sum(array_map(static fn(SupplierPayment $p)=>(float)$p->getAmount(),$sourceReceipts));$latest=$sourceReceipts[0]??null;$rows[]=['id'=>$key,'readingId'=>$reading->getId(),'paymentIndex'=>$index,'date'=>$reading->getWorkDate()?->format('Y-m-d'),'nozzle'=>$reading->getNozzle()?->getCode(),'responsible'=>$reading->getAttendant()?->getFullName(),'invoiceNumber'=>$reading->getInvoiceNumber(),'fuel'=>$reading->getNozzle()?->getTank()?->getFuelType()?->getCode(),'quantitySold'=>(float)$reading->getQuantitySold(),'unitPrice'=>(float)$reading->getUnitPrice(),'totalAmount'=>(float)$reading->getTotalAmount(),'customerName'=>$reading->getCustomer()?->getName(),'method'=>$line['type']??$line['label']??'—','methodLabel'=>$line['label']??$line['type']??'—','reference'=>$line['reference']??null,'amount'=>$amount,'received'=>$received,'remaining'=>max(0,$amount-$received),'status'=>$received>=$amount-.01?'RECEIVED':($received>0?'PARTIAL':'PENDING'),'supplier'=>$latest?->getSupplier()?->getName(),'settlementInvoiceNumber'=>$latest?->getSettlementInvoiceNumber(),'receivedDate'=>$latest?->getPaymentDate()?->format('Y-m-d')];}
  return $this->json(['deductions'=>$rows]);
 }
 #[Route('/deductions',methods:['POST'])]
 public function receiveDeduction(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse
 {
  if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;
  $d=$r->toArray();$reading=$em->getRepository(FuelShiftReading::class)->find((int)($d['readingId']??0));$supplier=$em->getRepository(Supplier::class)->find((int)($d['supplierId']??0));$index=(int)($d['paymentIndex']??-1);
  if(!$reading||!$supplier||!$supplier->isActive())return $this->json(['message'=>'Relevé et fournisseur actifs obligatoires'],422);
  if(!$access->canAccessStation($reading->getStation())||!$access->canAccessStation($supplier->getStation()))return$access->denyStation();
  if($reading->getStation()?->getId()!==$supplier->getStation()?->getId())return $this->json(['message'=>'Le fournisseur doit appartenir à la même station'],422);
  $lines=$reading->getPayments();$line=$lines[$index]??null;
  if(!is_array($line)||empty($line['supplierDeduction']))return $this->json(['message'=>'Cet encaissement n’est pas marqué comme paiement fournisseur'],422);
  $storedSalesInvoiceNumber=trim((string)($reading->getInvoiceNumber()??''));$requestedSalesInvoiceNumber=trim((string)($d['invoiceNumber']??''));if($storedSalesInvoiceNumber!==''&&$requestedSalesInvoiceNumber!==''&&$storedSalesInvoiceNumber!==$requestedSalesInvoiceNumber)return $this->json(['message'=>'Le numéro de facture ne correspond pas à celui du relevé'],422);$salesInvoiceNumber=$storedSalesInvoiceNumber?:$requestedSalesInvoiceNumber;$invoiceNumber=trim((string)($d['settlementInvoiceNumber']??''));if($salesInvoiceNumber==='')return $this->json(['message'=>'Le numéro de facture de vente est obligatoire'],422);if($invoiceNumber==='')return $this->json(['message'=>'Le numéro de facture ou d’avis du fournisseur est obligatoire'],422);
  $salesAmount=(float)($line['amount']??0);$received=0;$sourceReceipts=$em->getRepository(SupplierPayment::class)->findBy(['sourceReadingId'=>$reading->getId(),'sourcePaymentIndex'=>$index,'status'=>'RECEIVED']);foreach($sourceReceipts as $existing){if($existing->getSupplier()?->getId()!==$supplier->getId())return $this->json(['message'=>'Un encaissement ne peut être payé que par le même fournisseur'],422);$received+=(float)$existing->getAmount();}$remaining=$salesAmount-$received;$amount=round((float)($d['amount']??$remaining),2);
  if($amount<=0||$amount>$remaining+.01)return $this->json(['message'=>'Le montant reçu dépasse le solde de cet encaissement'],422);
  $payment=(new SupplierPayment())->setSupplier($supplier)->setInvoice(null)->setStation($reading->getStation())->setPerformedBy($access->currentUser())->setSourceReadingId($reading->getId())->setSourcePaymentIndex($index)->setSettlementInvoiceNumber($invoiceNumber)->setPaymentDate(new \DateTimeImmutable($d['date']??'today'))->setAmount((string)$amount)->setPaymentMethod('FOURNISSEUR')->setReference(trim((string)($d['reference']??''))?:null)->setStatus('RECEIVED')->setNote('Paiement fournisseur reçu pour facture '.$salesInvoiceNumber.' · relevé '.$reading->getId())->setCreatedAt(new \DateTimeImmutable());
  if(!$reading->getInvoiceNumber())$reading->setInvoiceNumber($salesInvoiceNumber);$em->persist($payment);$em->flush();return $this->json(['id'=>$payment->getId()],201);
 }
 #[Route('/{id}/deactivate',requirements:['id'=>'\\d+'],methods:['PATCH'])]public function deactivate(Supplier $s,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;if(!$access->canAccessStation($s->getStation()))return$access->denyStation();$s->setIsActive(false);$em->flush();return $this->json(['id'=>$s->getId()]);}
 #[Route('/payment-history',methods:['GET'])]public function paymentHistory(Request $r,EntityManagerInterface $em,UserAccessService $access):JsonResponse{if($denied=$access->require(UserAccessService::ROLE_GERANT))return$denied;$sid=(int)$r->query->get('station');if(!$access->canAccessStation($sid))return$access->denyStation();$payments=$em->getRepository(SupplierPayment::class)->findBy(['station'=>$sid],['paymentDate'=>'DESC','id'=>'DESC']);return $this->json(['payments'=>array_map(static fn(SupplierPayment $p)=>['id'=>$p->getId(),'invoiceId'=>$p->getInvoice()?->getId(),'invoice'=>$p->getInvoice()?->getInvoiceNumber(),'settlementInvoiceNumber'=>$p->getSettlementInvoiceNumber(),'supplier'=>$p->getSupplier()?->getName(),'date'=>$p->getPaymentDate()?->format('Y-m-d'),'amount'=>(float)$p->getAmount(),'method'=>$p->getPaymentMethod(),'reference'=>$p->getReference(),'note'=>$p->getNote(),'status'=>$p->getStatus(),'direction'=>$p->getStatus()==='RECEIVED'?'INCOMING':'OUTGOING'],$payments)]);}
}
