import {ChangeDetectorRef,Component,OnInit} from '@angular/core';
import {FormArray,FormBuilder,Validators} from '@angular/forms';
import {ArticleOptions,StationArticle} from '../../models/article.model';import {ArticleService} from '../../services/article.service';import {DropdownOption} from '../../shared/dropdown/dropdown';import {AuthService} from '../../services/auth.service';
@Component({selector:'app-articles',standalone:false,templateUrl:'./articles.html',styleUrl:'./articles.scss'})
export class Articles implements OnInit{
 items:StationArticle[]=[];options?:ArticleOptions;dropdownStations:DropdownOption[]=[];categoryOptions:DropdownOption[]=[];stationId=0;loading=true;showForm=false;saving=false;editing:StationArticle|null=null;toDeactivate:StationArticle|null=null;deactivating=false;quickType:'category'|null=null;quickForm;
 form;
 constructor(private service:ArticleService,private fb:FormBuilder,private cdr:ChangeDetectorRef,public auth:AuthService){this.form=fb.group({stationId:[0,[Validators.required,Validators.min(1)]],name:['',[Validators.required,Validators.minLength(2)]],description:[''],categoryId:[0,[Validators.required,Validators.min(1)]],currentStock:[0,[Validators.required,Validators.min(0)]],minimumStock:[0,[Validators.required,Validators.min(0)]],units:fb.array([])});this.quickForm=fb.nonNullable.group({name:['',Validators.required],code:[''],symbol:['']})}
 get units(){return this.form.controls.units as FormArray}
 ngOnInit(){this.refreshOptions()}
 refreshOptions(selectCategory?:number){this.service.options().subscribe(x=>{this.options=x;this.dropdownStations=x.stations.map(s=>({value:s.id,label:s.name,hint:'Point de vente actif'}));this.categoryOptions=x.categories.map(c=>({value:c.id,label:c.name}));if(!this.stationId){this.stationId=x.stations[0]?.id??0;this.form.patchValue({stationId:this.stationId});this.load()}if(selectCategory)this.form.patchValue({categoryId:selectCategory});this.cdr.detectChanges()})}
 load(){if(!this.stationId){this.loading=false;return}this.loading=true;this.service.list(this.stationId).subscribe(x=>{this.items=x;this.loading=false;this.cdr.detectChanges()})}
 addUnit(base=false,data?:any){if(base)this.units.controls.forEach(c=>c.patchValue({isBaseUnit:false}));this.units.push(this.fb.group({id:[data?.id??null],articleUnitId:[data?.articleUnitId??null],unitName:[data?.unitName??'',Validators.required],unitSymbol:[data?.unitSymbol??'',Validators.required],unitCode:[data?.unitCode??''],conversionFactor:[base?1:(data?.conversionFactor??1),[Validators.required,Validators.min(.000001)]],isBaseUnit:[base||!!data?.isBaseUnit],barcode:[data?.barcode??''],purchasePrice:[data?.purchasePrice??0,Validators.min(0)],salePrice:[data?.salePrice??0,[Validators.required,Validators.min(0)]],wholesalePrice:[data?.wholesalePrice??0,Validators.min(0)],minimumSalePrice:[data?.minimumSalePrice??0,Validators.min(0)]}))}
 setBase(index:number){this.units.controls.forEach((c,i)=>c.patchValue({isBaseUnit:i===index,conversionFactor:i===index?1:c.value.conversionFactor}))}
 removeUnit(index:number){if(this.units.length>1){const wasBase=this.units.at(index).value.isBaseUnit;this.units.removeAt(index);if(wasBase)this.setBase(0)}}
 open(item?:StationArticle){this.editing=item??null;this.units.clear();this.form.reset(item?{stationId:item.stationId,name:item.name,description:item.description??'',categoryId:item.categoryId??0,currentStock:item.currentStock,minimumStock:item.minimumStock}:{stationId:this.stationId,currentStock:0,minimumStock:0,categoryId:0});if(item?.units?.length)item.units.forEach(unit=>this.addUnit(false,unit));else this.addUnit(true);this.showForm=true}
 close(){if(!this.saving){this.showForm=false;this.editing=null}}
 openQuick(type:'category'){this.quickType=type;this.quickForm.reset()}
 saveQuick(){if(this.quickForm.invalid||!this.quickType)return;this.service.createCategory(this.quickForm.getRawValue()).subscribe(x=>{this.quickType=null;this.refreshOptions(x.id)})}
  submit(){if(this.form.invalid||!this.units.controls.some(c=>c.value.isBaseUnit)){this.form.markAllAsTouched();return}this.saving=true;const req=this.editing?this.service.update(this.editing.id,this.form.getRawValue() as any):this.service.create(this.form.getRawValue() as any);req.subscribe({next:x=>{this.items=this.editing?this.items.map(i=>i.id===x.id?x:i):[x,...this.items];this.saving=false;this.showForm=false;this.editing=null;this.form.reset({stationId:this.stationId,currentStock:0,minimumStock:0,categoryId:0});this.units.clear();this.cdr.detectChanges()},error:()=>{this.saving=false;this.cdr.detectChanges()}})}
 confirmDeactivate(item:StationArticle){this.toDeactivate=item}
 deactivate(){if(!this.toDeactivate)return;this.deactivating=true;this.service.deactivate(this.toDeactivate.id).subscribe({next:x=>{this.items=this.items.map(i=>i.id===x.id?x:i);this.toDeactivate=null;this.deactivating=false;this.cdr.detectChanges()},error:()=>{this.deactivating=false;this.cdr.detectChanges()}})}
}
